name: Python CI with MongoDB

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ACTIONS_RUNTIME_TOKEN: ${{ secrets.ACTIONS_RUNTIME_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest-cov

      - name: Lint with flake8
        run: flake8 . || true

      - name: Check formatting with black
        run: black --check . || true

      - name: Run tests with coverage and print summary
        run: |
          pytest --cov=. --cov-report=term

      - name: Run tests with coverage (HTML report)
        run: |
          pytest --cov=. --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

      - name: Enable debug logging
        run: echo "ACT_DEBUG=true" >> $GITHUB_ENV
